### ISSUE TITLE
Is "Strenght" Deliberate?

### ISSUE THREAD

**Issue by henricj** [NetDevPack/Security.PasswordHasher#213]
The word "strenght" is usually spelled "strength."  Is the use of this alternate spelling intentional?

For example, the `.WithStrenghten()` and the `PasswordHasherStrenght.Interactive` in:
```C#
    services.UpgradePasswordSecurity()
                    .WithStrenghten(PasswordHasherStrenght.Interactive)
                    .UseArgon2<IdentityUser>();
```

**Comment by brunobritodev** [comment]
No, definetely isn't intentional.
