### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by jongon** [NetDevPack/Security.PasswordHasher#84]
I Had to remove this library JPProject SSO solution by performance issues

**Comment by brunobritodev** [comment]
The goal of password Hash algorithm is to be slow as hell. By this way you can mitigate attacks at your users passwords in case of your database got in wrong hands.

You can change the Algorithm performance in this way:
``` c#
services.UpgradePasswordSecurity()
                    .WithStrenghten(PasswordHasherStrenght.Interactive)
                    .UseArgon2<IdentityUser>();
```

Argon2 is the most recommended password Hash by OWASP.

Anyway, if you remove it, the algorithm will become the default from ASP.NET Identity. Which is PBKDF2.
