### ISSUE TITLE
Update Sodium.Core to avoid ASCII 0 issues

### ISSUE THREAD

**Issue by Atulin** [NetDevPack/Security.PasswordHasher#94]
Relevant issue in Sodium.Core repo: https://github.com/tabrath/libsodium-core/issues/46

**Comment by brunobritodev** [comment]
Thanks, I'm waiting for a fix

**Comment by Atulin** [comment]
The fix is there, in 1.2.3. Just gotta update the NuGet

**Comment by Atulin** [comment]
Seems I was mistaken. I forked another Argon2 hasher (https://github.com/Atulin/Argon2PasswordHasher) and updated Sodium, but I still get a PostgresException 22021, incorrect encoding sequence for "UTF8": 0x00

**Comment by brunobritodev** [comment]
Btw I got this bug before and version 3.0.2 was treating ASCI 0 to fix bug in EF postgre driver. Now the version 3.0.3 has an upgrade of Sodium core.
